name: kafka
description: Apache Kafka Message Queue
region: cn-north-4
project: {project}
function:
  name: kafka
  description: Apache Kafka Message Queue
  runtime: CustomImage
  handler: ''
  memorySize: 4096
  timeout: 600
  codeType: CustomImage
  customImage:
    image: confluentinc/cp-kafka:latest
    port: 9092
  environmentVariables:
    KAFKA_ZOOKEEPER_CONNECT: localhost:2181

  vpcId: ''
  subnetId: ''
  enterpriseProjectId: default
  agency: ''
  xrole: ''
  concurrency:
    strategy: dynamic
    maxConcurrent: 100
  triggers:
    - triggerType: APIG
      eventData:
        auth: IAM
        name: kafka-apig
        protocol: HTTP
        timeout: 5000
