appId: {appId}
component: scf
name: postgresql
stage: prod
org: {org}
app: postgresql-app
inputs:
  name: postgresql
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: CustomContainer
  description: PostgreSQL Database
  namespace: default
  type: web
  memorySize: 2048
  timeout: 300
  initTimeout: 300
  cls:
    logsetId: ''
    topicId: ''
  layers: []
  environment:
    variables:

  containerConf:
    image: postgres:latest
    containerPort: 5432
    imageTag: latest
  vpcConfig:
    vpcId: ''
    subnetId: ''
  triggers:
    - type: apigw
      parameters:
        name: postgresql-apigw
        protocols:
          - http
          - https
        serviceName: serverless
        description: API Gateway trigger for postgresql
        environment: release
        endPoints:
          - path: /
            method: ANY
