replicaCount: 1

image:
  repository: kong
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

services:
  kong:
    type: ClusterIP
    ports:
      - name: admin
        port: 8001
        targetPort: 8001
      - name: proxy
        port: 8000
        targetPort: 8000
      - name: ssl
        port: 8443
        targetPort: 8443
  konga:
    enabled: true
    type: ClusterIP
    port: 1337

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  KONG_DATABASE: "postgres"
  KONG_PG_HOST: "postgres"
  KONG_PG_PASSWORD: "kong"
  KONG_PG_DATABASE: "kong"
  KONG_PROXY_LISTEN: "0.0.0.0:8000"
  KONG_ADMIN_LISTEN: "0.0.0.0:8001"
  DB_ADAPTER: "postgres"
  DB_HOST: "postgres"
  DB_USER: "kong"
  DB_DATABASE: "konga"
  DB_PASSWORD: "konga"
