name: memcached
description: Memcached Cache Service
region: cn-north-4
project: {project}
function:
  name: memcached
  description: Memcached Cache Service
  runtime: CustomImage
  handler: ''
  memorySize: 1024
  timeout: 300
  codeType: CustomImage
  customImage:
    image: memcached:latest
    port: 11211
  environmentVariables:

  vpcId: ''
  subnetId: ''
  enterpriseProjectId: default
  agency: ''
  xrole: ''
  concurrency:
    strategy: dynamic
    maxConcurrent: 100
  triggers:
    - triggerType: APIG
      eventData:
        auth: IAM
        name: memcached-apig
        protocol: HTTP
        timeout: 5000
