apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kong-gateway.fullname" . }}-kong
  labels:
    {{- include "kong-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kong-gateway.selectorLabels" . | nindent 6 }}
      component: kong
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kong-gateway.selectorLabels" . | nindent 8 }}
        component: kong
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kong-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kong
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: admin
              containerPort: 8001
              protocol: TCP
            - name: proxy
              containerPort: 8000
              protocol: TCP
            - name: ssl
              containerPort: 8443
              protocol: TCP
          env:
            - name: KONG_DATABASE
              value: {{ .Values.config.KONG_DATABASE }}
            - name: KONG_PG_HOST
              value: {{ .Values.config.KONG_PG_HOST }}
            - name: KONG_PG_PASSWORD
              value: {{ .Values.config.KONG_PG_PASSWORD }}
            - name: KONG_PG_DATABASE
              value: {{ .Values.config.KONG_PG_DATABASE }}
            - name: KONG_PROXY_LISTEN
              value: {{ .Values.config.KONG_PROXY_LISTEN }}
            - name: KONG_ADMIN_LISTEN
              value: {{ .Values.config.KONG_ADMIN_LISTEN }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kong-gateway.fullname" . }}-konga
  labels:
    {{- include "kong-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kong-gateway.selectorLabels" . | nindent 6 }}
      component: konga
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kong-gateway.selectorLabels" . | nindent 8 }}
        component: konga
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kong-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: konga
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "pantsel/konga:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1337
              name: http
              protocol: TCP
          env:
            - name: DB_ADAPTER
              value: {{ .Values.config.DB_ADAPTER }}
            - name: DB_HOST
              value: {{ .Values.config.DB_HOST }}
            - name: DB_USER
              value: {{ .Values.config.DB_USER }}
            - name: DB_DATABASE
              value: {{ .Values.config.DB_DATABASE }}
            - name: DB_PASSWORD
              value: {{ .Values.config.DB_PASSWORD }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
