name: mssql
description: Microsoft SQL Server
region: cn-north-4
project: {project}
function:
  name: mssql
  description: Microsoft SQL Server
  runtime: CustomImage
  handler: ''
  memorySize: 4096
  timeout: 600
  codeType: CustomImage
  customImage:
    image: mcr.microsoft.com/mssql/server:2022-latest
    port: 1433
  environmentVariables:
    ACCEPT_EULA: Y

  vpcId: ''
  subnetId: ''
  enterpriseProjectId: default
  agency: ''
  xrole: ''
  concurrency:
    strategy: dynamic
    maxConcurrent: 100
  triggers:
    - triggerType: APIG
      eventData:
        auth: IAM
        name: mssql-apig
        protocol: HTTP
        timeout: 5000
