apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash-kibana.logstash.fullname" . }}
  labels:
    {{- include "logstash-kibana.labels" . | nindent 4 }}
    component: logstash
spec:
  type: {{ .Values.logstash.service.type }}
  ports:
    {{- toYaml .Values.logstash.service.ports | nindent 4 }}
  selector:
    {{- include "logstash-kibana.selectorLabels" . | nindent 4 }}
    component: logstash
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash-kibana.kibana.fullname" . }}
  labels:
    {{- include "logstash-kibana.labels" . | nindent 4 }}
    component: kibana
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: 5601
      name: http
  selector:
    {{- include "logstash-kibana.selectorLabels" . | nindent 4 }}
    component: kibana
