apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio.labels" . | nindent 4 }}
spec:
  mtls:
    mode: {{ .Values.security.mTLS.mode }}
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio.labels" . | nindent 4 }}
{{- if .Values.security.jwtPolicy.enabled }}
spec:
  jwtRules:
    - issuer: {{ .Values.security.jwtPolicy.issuer }}
      audiences:
        - {{ include "istio.fullname" . }}
      forwardOriginalRequestAuthorizationHeader: true
      triggerRules:
        - excludedPaths:
            - prefix: /health
            - prefix: /ready
{{- end }}
