apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "istio.istiod.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "istio.gateway.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio.labels" . | nindent 4 }}
