apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio.labels" . | nindent 4 }}
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        h2UpgradePolicy: UPGRADE
        http1MaxPendingRequests: 100
        http2MaxRequests: 1000
    loadBalancer:
      simple: LEAST_REQUEST
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gateway-vs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio.labels" . | nindent 4 }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ include "istio.gateway.fullname" . }}/http-gateway
  http:
    - match:
        - uri:
            prefix: /health
      route:
        - destination:
            host: kubernetes.default.svc.cluster.local
            port:
              number: 80
    - match:
        uri:
          prefix: /nacos
      route:
        - destination:
            host: nacos-server
            port:
              number: 8848
    - match:
        uri:
          prefix: /skywalking
      route:
        - destination:
            host: skywalking-ui
            port:
              number: 8080
