name: mongodb
description: MongoDB NoSQL Database
region: cn-north-4
project: {project}
function:
  name: mongodb
  description: MongoDB NoSQL Database
  runtime: CustomImage
  handler: ''
  memorySize: 2048
  timeout: 300
  codeType: CustomImage
  customImage:
    image: mongo:latest
    port: 27017
  environmentVariables:

  vpcId: ''
  subnetId: ''
  enterpriseProjectId: default
  agency: ''
  xrole: ''
  concurrency:
    strategy: dynamic
    maxConcurrent: 100
  triggers:
    - triggerType: APIG
      eventData:
        auth: IAM
        name: mongodb-apig
        protocol: HTTP
        timeout: 5000
