name: redis
description: Redis Cache
region: cn-north-4
project: {project}
function:
  name: redis
  description: Redis Cache
  runtime: CustomImage
  handler: ''
  memorySize: 1024
  timeout: 300
  codeType: CustomImage
  customImage:
    image: redis:latest
    port: 6379
  environmentVariables:

  vpcId: ''
  subnetId: ''
  enterpriseProjectId: default
  agency: ''
  xrole: ''
  concurrency:
    strategy: dynamic
    maxConcurrent: 100
  triggers:
    - triggerType: APIG
      eventData:
        auth: IAM
        name: redis-apig
        protocol: HTTP
        timeout: 5000
