appId: {appId}
component: scf
name: redis
stage: prod
org: {org}
app: redis-app
inputs:
  name: redis
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: CustomContainer
  description: Redis Cache
  namespace: default
  type: web
  memorySize: 1024
  timeout: 300
  initTimeout: 300
  cls:
    logsetId: ''
    topicId: ''
  layers: []
  environment:
    variables:

  containerConf:
    image: redis:latest
    containerPort: 6379
    imageTag: latest
  vpcConfig:
    vpcId: ''
    subnetId: ''
  triggers:
    - type: apigw
      parameters:
        name: redis-apigw
        protocols:
          - http
          - https
        serviceName: serverless
        description: API Gateway trigger for redis
        environment: release
        endPoints:
          - path: /
            method: ANY
