appId: {appId}
component: scf
name: it-tools
stage: prod
org: {org}
app: it-tools-app
inputs:
  name: it-tools
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: CustomContainer
  description: IT Tools
  namespace: default
  type: web
  memorySize: 1024
  timeout: 300
  initTimeout: 300
  cls:
    logsetId: ''
    topicId: ''
  layers: []
  environment:
    variables:

  containerConf:
    image: corentinth/it-tools:latest
    containerPort: 80
    imageTag: latest
  vpcConfig:
    vpcId: ''
    subnetId: ''
  triggers:
    - type: apigw
      parameters:
        name: it-tools-apigw
        protocols:
          - http
          - https
        serviceName: serverless
        description: API Gateway trigger for it-tools
        environment: release
        endPoints:
          - path: /
            method: ANY
