networks:
    structure-cloud-work:
        external: true
services:
    postgresql:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
            placement:
              constraints:
                - node.role == master
        environment:
            - POSTGRES_USER=${PANEL_DB_ROOT_USER}
            - POSTGRES_PASSWORD=${PANEL_DB_ROOT_PASSWORD}
        healthcheck:
            interval: 30s
            retries: 5
            start_period: 20s
            test:
                - CMD
                - pg_isready
                - -h
                - 127.0.0.1
                - -p
                - "5432"
                - -q
                - -U
                - ${PANEL_DB_ROOT_USER}
            timeout: 5s
        image: postgres:17.1-alpine
        labels:
            createdBy: Apps
        networks:
            - structure-cloud-work
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:5432
        restart: always
        volumes:
            - ${PWD}/data:/var/lib/postgresql/data
