apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    url: http://elasticsearch:9200
    database: logs-*
    version: 8
    editable: true
    jsonData:
      timeField: "@timestamp"
      esVersion: 8
      logMessageField: message
      maxConcurrentShardRequests: 5

  - name: SkyWalking
    type: prometheus
    access: proxy
    orgId: 1
    url: http://skywalking-oap:12800
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
