networks:
    structure-cloud-work:
        external: true
services:
    oap:
        container_name: skywalking-oap
        image: apache/skywalking-oap-server:9.7.0
        hostname: oap
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 4G
            placement:
                constraints:
                    - node.role == worker
        networks:
            - structure-cloud-work
        environment:
            - SW_STORAGE=elasticsearch
            - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
            - SW_ES_USER=elastic
            - SW_ES_PASSWORD=Elastic_aXbnMp
            - JAVA_OPTS=-Xms2g -Xmx2g
        volumes:
            - ${PWD}/data:/data
        ports:
            - 11800:11800  # gRPC receiver
            - 12800:12800  # REST API
        restart: always

    ui:
        container_name: skywalking-ui
        image: apache/skywalking-ui:9.7.0
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 1G
            placement:
                constraints:
                    - node.role == worker
        networks:
            - structure-cloud-work
        environment:
            - SW_OAP_ADDRESS=http://oap:12800
        ports:
            - 28080:8080
        restart: always
