apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbitmq3.fullname" . }}
  labels:
    {{- include "rabbitmq3.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rabbitmq3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rabbitmq3.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rabbitmq3.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: prometheus
              containerPort: 15692
              protocol: TCP
            - name: clustering
              containerPort: 25672
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_VHOST
              value: {{ .Values.config.RABBITMQ_DEFAULT_VHOST }}
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.config.RABBITMQ_DEFAULT_USER }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.config.RABBITMQ_DEFAULT_PASS }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: rabbitmq3-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq3-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "rabbitmq3.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
