networks:
  structure-cloud-work:
        external: true
services:
    clickhouse:
        container_name: clickhouse
        deploy:
            resources:
                limits:
                    cpus: 0
                    memory: 0
            placement:
                constraints:
                    - node.role == master
        image: clickhouse/clickhouse-server:24.10.1-alpine
        labels:
            createdBy: Apps
        networks:
          - structure-cloud-work
        ports:
            - 18123:8123
            - 19000:9000
        restart: always
        ulimits:
            nofile:
                hard: 262144
                soft: 262144
        volumes:
            - ./clickhouse:/var/lib/clickhouse/
            - ./clickhouse-server:/var/log/clickhouse-server/
