networks:
    structure-cloud-work:
        external: true
services:
    logstash:
        container_name: structure-logstash
        image: logstash:8.16.0
        deploy:
            resources:
                limits:
                    cpus: 2
                    memory: 2G
            placement:
                constraints:
                    - node.role == master
        networks:
            - structure-cloud-work
        volumes:
            - ./pipeline:/usr/share/logstash/pipeline
            - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
            - ./logs:/var/log/app
        ports:
            - "5044:5044"
            - "9600:9600"
        environment:
            - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
            - "XPACK_MONITORING_ENABLED=true"
        restart: always

    kibana:
        container_name: structure-kibana
        image: kibana:8.16.0
        deploy:
            resources:
                limits:
                    cpus: 1
                    memory: 1G
            placement:
                constraints:
                    - node.role == worker
        networks:
            - structure-cloud-work
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=123456
            - SERVER_NAME=kibana.local
            - XPACK_SECURITY_ENABLED=false
        restart: always

