apiVersion: v1
kind: Service
metadata:
  name: {{ include "skywalking.oap.fullname" . }}
  labels:
    {{- include "skywalking.labels" . | nindent 4 }}
    component: oap
spec:
  type: {{ .Values.oap.service.type }}
  ports:
    {{- toYaml .Values.oap.service.ports | nindent 4 }}
  selector:
    {{- include "skywalking.selectorLabels" . | nindent 4 }}
    component: oap
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skywalking.ui.fullname" . }}
  labels:
    {{- include "skywalking.labels" . | nindent 4 }}
    component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "skywalking.selectorLabels" . | nindent 4 }}
    component: ui
