name: rocketmq
description: RocketMQ Message Queue
region: cn-north-4
project: {project}
function:
  name: rocketmq
  description: RocketMQ Message Queue
  runtime: CustomImage
  handler: ''
  memorySize: 4096
  timeout: 600
  codeType: CustomImage
  customImage:
    image: apache/rocketmq:latest
    port: 9876
  environmentVariables:

  vpcId: ''
  subnetId: ''
  enterpriseProjectId: default
  agency: ''
  xrole: ''
  concurrency:
    strategy: dynamic
    maxConcurrent: 100
  triggers:
    - triggerType: APIG
      eventData:
        auth: IAM
        name: rocketmq-apig
        protocol: HTTP
        timeout: 5000
