name: postgres
description: PostgreSQL Database
region: cn-north-4
project: {project}
function:
  name: postgres
  description: PostgreSQL Database
  runtime: CustomImage
  handler: ''
  memorySize: 2048
  timeout: 300
  codeType: CustomImage
  customImage:
    image: postgres:latest
    port: 5432
  environmentVariables:

  vpcId: ''
  subnetId: ''
  enterpriseProjectId: default
  agency: ''
  xrole: ''
  concurrency:
    strategy: dynamic
    maxConcurrent: 100
  triggers:
    - triggerType: APIG
      eventData:
        auth: IAM
        name: postgres-apig
        protocol: HTTP
        timeout: 5000
