{{- if .Values.istio_gateway.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "istio.gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "istio.gateway.fullname" . }}
  minReplicas: {{ .Values.istio_gateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.istio_gateway.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.istio_gateway.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
