networks:
    structure-cloud-work:
        external: true
services:
    it-tools:
        container_name: ${CONTAINER_NAME}

        image: corentinth/it-tools:2024.10.22-7ca5933
        labels:
            createdBy: Apps
        networks:
            - structure-cloud-work
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:80
        restart: always
