appId: {appId}
component: scf
name: nginx
stage: prod
org: {org}
app: nginx-app
inputs:
  name: nginx
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: CustomContainer
  description: Nginx Web Server
  namespace: default
  type: web
  memorySize: 1024
  timeout: 300
  initTimeout: 300
  cls:
    logsetId: ''
    topicId: ''
  layers: []
  environment:
    variables:

  containerConf:
    image: nginx:latest
    containerPort: 80
    imageTag: latest
  vpcConfig:
    vpcId: ''
    subnetId: ''
  triggers:
    - type: apigw
      parameters:
        name: nginx-apigw
        protocols:
          - http
          - https
        serviceName: serverless
        description: API Gateway trigger for nginx
        environment: release
        endPoints:
          - path: /
            method: ANY
