networks:
    structure-cloud-work:
        external: true
services:
    mysql:
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --lower_case_table_names=1
        container_name: "structure-mysql"
        deploy:
            placement:
              constraints:
                - node.role == manager
        environment:
            MYSQL_ROOT_PASSWORD: "mysql_8cAASM"
        image: mysql:5.7.44
        labels:
            createdBy: Apps
        networks:
            - structure-cloud-work
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ${PWD}/data:/var/lib/mysql
            - ${PWD}/logs:/var/log/mysql/
            - ${PWD}/init.d:/docker-entrypoint-initdb.d/:ro
            - ${PWD}/config:/etc/mysql/conf.d/:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
