networks:
    structure-cloud-work:
        external: true
services:
    mysql:
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --lower_case_table_names=1
        container_name: "structure-mysql"
        deploy:
            resources:
                limits:
                    cpus: 0
                    memory: 0
            placement:
              constraints:
                - node.role == manager
        environment:
            MYSQL_ROOT_PASSWORD: "mysql_8cAASM"
        image: mysql:5.7.44
        labels:
            createdBy: Apps
        networks:
            - structure-cloud-work
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ${PWD}/data/:/var/lib/mysql
            - ${PWD}/conf/my.cnf:/etc/mysql/my.cnf
            - ${PWD}/log:/var/log/mysql
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
