name: {{service_name}}
description: {{service_description}}
region: cn-north-4
project: {{project}}
function:
  name: {{service_name}}
  description: {{service_description}}
  runtime: CustomImage
  handler: ''
  memorySize: {{memory}}
  timeout: {{timeout}}
  codeType: CustomImage
  customImage:
    image: {{image}}
    port: {{port}}
  environmentVariables:
{{#each env_vars}}
    {{key}}: {{value}}
{{/each}}
  vpcId: ''
  subnetId: ''
  enterpriseProjectId: default
  agency: ''
  xrole: ''
  concurrency:
    strategy: dynamic
    maxConcurrent: 100
  triggers:
    - triggerType: APIG
      eventData:
        auth: IAM
        name: {{service_name}}-apig
        protocol: HTTP
        timeout: 5000
