apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alertmanager-grafana.serviceAccountName" . }}
  labels:
    {{- include "alertmanager-grafana.labels" . | nindent 4 }}
{{- end }}

{{- define "alertmanager-grafana.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- .Values.serviceAccount.name | default (include "alertmanager-grafana.fullname" .) }}
{{- else }}
{{- .Values.serviceAccount.name | default "default" }}
{{- end }}
{{- end }}
