version: '3.8'
services:
  kong-migration:
    image: kong/kong-gateway:3.9.0.0
    command: "kong migrations bootstrap"
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    networks:
      - structure-cloud-work
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=root
      - KONG_PG_PASSWORD=123456
      - KONG_PG_HOST=postgres
networks:
  structure-cloud-work:
    external: true
