version: '3.8'
services:
  redis:
    image: redis:6.2.16
    container_name: redis
    restart: always
    privileged: true
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      - structure-cloud-work
    ports:
      - "6379:6379"
    volumes:
      - ${PWD}/data:/data
      - ${PWD}/conf/redis.conf:/etc/redis/redis.conf
      - ${PWD}/logs:/logs
    command:
      redis-server  /etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
networks:
  structure-cloud-work:
    external: true