apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-gateway.fullname" . }}-kong
  labels:
    {{- include "kong-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.kong.type }}
  ports:
    {{- range .Values.services.kong.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "kong-gateway.selectorLabels" . | nindent 4 }}
    component: kong
---
{{- if .Values.services.konga.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-gateway.fullname" . }}-konga
  labels:
    {{- include "kong-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.konga.type }}
  ports:
    - port: {{ .Values.services.konga.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kong-gateway.selectorLabels" . | nindent 4 }}
    component: konga
{{- end }}
