version: '3.8'
services:
  #######################
  # 执行数据库迁移
  ######################
  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    env_file:
      - .env
    networks:
      - structure-cloud-work
    restart: on-failure
    environment:
      - KONG_DATABASE=${KONG_DATABASE}
      - KONG_PG_DATABASE=${KONG_PG_DATABASE}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
      - KONG_PG_HOST=${KONG_PG_HOST}
    depends_on:
      - postgres

  #####################
  # kong gateway
  #####################
  kong:
    image: kong:latest
    hostname: kong
    restart: always
    env_file:
      - .env
    networks:
      - structure-cloud-work
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PROXY_LISTEN: ${KONG_PROXY_LISTEN}
      KONG_PROXY_LISTEN_SSL: ${KONG_PROXY_LISTEN_SSL}
      KONG_ADMIN_LISTEN: ${KONG_ADMIN_LISTEN}
    depends_on:
      - kong-migration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "${KONG_ADMIN_PORT}:8001"
      - "${KONG_PORT}:8000"
      - "${KONG_SSL_PORT}:8443"

  #######################
  # konga GUI
  #######################
  konga:
    image: pantsel/konga:latest
    restart: always
    env_file:
      - .env
    networks:
      - structure-cloud-work
    environment:
      DB_ADAPTER: ${DB_ADAPTER}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - kong
    ports:
      - "${KONGA_PORT}:1337"

networks:
  structure-cloud-work:
    external: true
