replicaCount: 1

image:
  repository: mcr.microsoft.com/mssql/server
  pullPolicy: IfNotPresent
  tag: "2022-latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 1433

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  size: 10Gi
  storageClass: ""

config:
  MSSQL_SA_PASSWORD: "YourPassword123!"
  ACCEPT_EULA: "Y"
