apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kafka.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kafka.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9092
              name: kafka
              protocol: TCP
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: {{ .Values.config.ALLOW_PLAINTEXT_LISTENER }}
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: {{ .Values.config.KAFKA_CFG_ADVERTISED_LISTENERS }}
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: {{ .Values.config.KAFKA_CFG_CONTROLLER_LISTENER_NAMES }}
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: {{ .Values.config.KAFKA_CFG_CONTROLLER_QUORUM_VOTERS }}
            - name: KAFKA_CFG_FETCH_MESSAGE_MAX_BYTES
              value: {{ .Values.config.KAFKA_CFG_FETCH_MESSAGE_MAX_BYTES }}
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: {{ .Values.config.KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP }}
            - name: KAFKA_CFG_LISTENERS
              value: {{ .Values.config.KAFKA_CFG_LISTENERS }}
            - name: KAFKA_CFG_LOG_RETENTION_MS
              value: {{ .Values.config.KAFKA_CFG_LOG_RETENTION_MS }}
            - name: KAFKA_CFG_MAX_REQUEST_SIZE
              value: {{ .Values.config.KAFKA_CFG_MAX_REQUEST_SIZE }}
            - name: KAFKA_CFG_MESSAGE_MAX_BYTES
              value: {{ .Values.config.KAFKA_CFG_MESSAGE_MAX_BYTES }}
            - name: KAFKA_CFG_NODE_ID
              value: {{ .Values.config.KAFKA_CFG_NODE_ID | quote }}
            - name: KAFKA_CFG_PARTITION_FETCH_BYTES
              value: {{ .Values.config.KAFKA_CFG_PARTITION_FETCH_BYTES }}
            - name: KAFKA_CFG_PROCESS_ROLES
              value: {{ .Values.config.KAFKA_CFG_PROCESS_ROLES }}
            - name: KAFKA_CFG_REPLICA_FETCH_MAX_BYTES
              value: {{ .Values.config.KAFKA_CFG_REPLICA_FETCH_MAX_BYTES }}
            - name: KAFKA_HEAP_OPTS
              value: {{ .Values.config.KAFKA_HEAP_OPTS }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
      volumes:
        - name: kafka-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "kafka.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
