name: neo4j
description: Neo4j Graph Database
region: cn-north-4
project: {project}
function:
  name: neo4j
  description: Neo4j Graph Database
  runtime: CustomImage
  handler: ''
  memorySize: 2048
  timeout: 300
  codeType: CustomImage
  customImage:
    image: neo4j:latest
    port: 7474
  environmentVariables:

  vpcId: ''
  subnetId: ''
  enterpriseProjectId: default
  agency: ''
  xrole: ''
  concurrency:
    strategy: dynamic
    maxConcurrent: 100
  triggers:
    - triggerType: APIG
      eventData:
        auth: IAM
        name: neo4j-apig
        protocol: HTTP
        timeout: 5000
