apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstash-kibana.logstash.fullname" . }}-pipeline
  labels:
    {{- include "logstash-kibana.labels" . | nindent 4 }}
data:
  logstash.conf: |
{{ .Values.logstash.pipeline.logstash.conf | indent 4 }}
