apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logstash-kibana.serviceAccountName" . }}
  labels:
    {{- include "logstash-kibana.labels" . | nindent 4 }}
{{- end }}

{{- define "logstash-kibana.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- .Values.serviceAccount.name | default (include "logstash-kibana.fullname" .) }}
{{- else }}
{{- .Values.serviceAccount.name | default "default" }}
{{- end }}
{{- end }}
