networks:
    structure-cloud-work:
        external: true
services:
    openldap:
        container_name: ${CONTAINER_NAME}

        environment:
            LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
            LDAP_ADMIN_USERNAME: ${LDAP_ADMIN_USERNAME}
            LDAP_ROOT: ${LDAP_ROOT}
        image: bitnami/openldap:2.6.8
        labels:
            createdBy: Apps
        networks:
            - structure-cloud-work
        ports:
            - ${HOST_IP}:${LDAP_PORT}:1389
        restart: always
        volumes:
            - ${PWD}/data:/bitnami/openldap
version: "3"
