appId: {appId}
component: scf
name: prometheus
stage: prod
org: {org}
app: prometheus-app
inputs:
  name: prometheus
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: CustomContainer
  description: Prometheus Monitoring
  namespace: default
  type: web
  memorySize: 2048
  timeout: 300
  initTimeout: 300
  cls:
    logsetId: ''
    topicId: ''
  layers: []
  environment:
    variables:

  containerConf:
    image: prom/prometheus:latest
    containerPort: 9090
    imageTag: latest
  vpcConfig:
    vpcId: ''
    subnetId: ''
  triggers:
    - type: apigw
      parameters:
        name: prometheus-apigw
        protocols:
          - http
          - https
        serviceName: serverless
        description: API Gateway trigger for prometheus
        environment: release
        endPoints:
          - path: /
            method: ANY
