appId: {appId}
component: scf
name: mariadb
stage: prod
org: {org}
app: mariadb-app
inputs:
  name: mariadb
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: CustomContainer
  description: MariaDB Database
  namespace: default
  type: web
  memorySize: 2048
  timeout: 300
  initTimeout: 300
  cls:
    logsetId: ''
    topicId: ''
  layers: []
  environment:
    variables:

  containerConf:
    image: mariadb:latest
    containerPort: 3306
    imageTag: latest
  vpcConfig:
    vpcId: ''
    subnetId: ''
  triggers:
    - type: apigw
      parameters:
        name: mariadb-apigw
        protocols:
          - http
          - https
        serviceName: serverless
        description: API Gateway trigger for mariadb
        environment: release
        endPoints:
          - path: /
            method: ANY
