apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-namesrv
  labels:
    {{- include "rocketmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.namesrv.type }}
  ports:
    - port: {{ .Values.services.namesrv.port }}
      targetPort: namesrv
      protocol: TCP
      name: namesrv
  selector:
    {{- include "rocketmq.selectorLabels" . | nindent 4 }}
    component: namesrv
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-broker
  labels:
    {{- include "rocketmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.broker.type }}
  ports:
    {{- range .Values.services.broker.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "rocketmq.selectorLabels" . | nindent 4 }}
    component: broker
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-dashboard
  labels:
    {{- include "rocketmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.dashboard.type }}
  ports:
    - port: {{ .Values.services.dashboard.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rocketmq.selectorLabels" . | nindent 4 }}
    component: dashboard
